# serverless.yml
service: cashew
provider:
  name: aws
  runtime: nodejs6.10
  credentials: ${file(./.env.yml):credentials}
functions:
  api:
    handler: cashew.handler
    events:
      - http: ANY {proxy+}